version: 2

jobs:
  run-python-tests:
  # flake8 and test unit tests
    docker:
      - image: circleci/python:3.6
        environment:
          PYTHONUNBUFFERED: 1
          DJANGO_SETTINGS_MODULE: config.settings.dev
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev --system
            flake8
            python manage.py test

  deploy-to-staging:
  # deploy to https://staging.kevinharper.com/
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a6:fc:3f:ab:e9:d6:02:96:30:69:59:ac:54:f7:ec:b3"
      - run:
          name: "Deploy to Staging"
          command: |
            ssh $STAGING_USER@$STAGING_HOST << EOF

              cd sites/staging-kevinharper-com
              git clone https://github.com/khdc-me/ws-kevinharper.git
              cd ws-kevinharper

            EOF


#  deploy-to-prod:
#  # deploy to https://kevinharper.com/
#  #   on Digital Ocean

workflows:
  version: 2
  test-local_deploy-stage_deploy-prod:
    jobs:
      - run-python-tests
      - review-PR:
          # Visually check code changes that were
          #   submitted via PR
          type: approval
          requires:
            - run-python-tests
      - deploy-to-staging:
         requires:
           - review-PR
      - review-staging:
          # Visually check site
          type: approval
          requires:
            - deploy-to-staging
#      - deploy-to-prod:
#          filters:
#            branches:
#              only: master
