version: 2

jobs:
  run-python-tests:
  # flake8 and test unit tests
    docker:
      - image: circleci/python:3.6
        environment:
          PYTHONUNBUFFERED: 1
          DJANGO_SETTINGS_MODULE: config.settings.settings
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev --system
            flake8
            python manage.py test

  deploy-to-staging:
  # deploy to https://staging.kevinharper.com/
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "a6:fc:3f:ab:e9:d6:02:96:30:69:59:ac:54:f7:ec:b3"
      - run:
          name: "Build and push staging image to Docker Hub"
          command: |
            echo "$DOCKER_PASSWD" | docker login --username $DOCKER_USER --password-stdin
            docker build -t khdcme/www-kevinharper-com:staging .
            docker push khdcme/www-kevinharper-com:staging            
      - run:
          name: "Deploy to Staging"
          command: |
            ssh $STAGING_USER@$STAGING_HOST << EOF
              docker-compose -f sites/staging-kevinharper-com/docker-compose.yml up -d
            EOF


  deploy-to-prod:
  # deploy to https://kevinharper.com/
  #   on Digital Ocean
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "a6:fc:3f:ab:e9:d6:02:96:30:69:59:ac:54:f7:ec:b3"
      - run:
          name: "Purge from Staging"
          command: |
            ssh $STAGING_USER@$STAGING_HOST << EOF
              docker-compose -f sites/staging-kevinharper-com/docker-compose.yml down \
              && docker rmi khdcme/www-kevinharper-com:staging
            EOF
      - run:
          name: "Build and push latest image to Docker Hub"
          command: |
            echo "$DOCKER_PASSWD" | docker login --username $DOCKER_USER --password-stdin
            docker build -t khdcme/www-kevinharper-com:latest .
            docker push khdcme/www-kevinharper-com:latest
      - run:
          name: "Deploy to Production"
          command: |
            ssh $PROD_USER@$PROD_HOST << EOF
              docker-compose -f sites/www-kevinharper-com/docker-compose.yml up -d
            EOF

workflows:
  version: 2
  test-local_deploy-stage_deploy-prod:
    jobs:
      - run-python-tests:
          filters:
            branches:
              ignore: master
      - review-PR:
          filters:
            branches:
              ignore: master
          # Visually check code changes that were
          #   submitted via PR
          type: approval
          requires:
            - run-python-tests
      - deploy-to-staging:
          filters:
            branches:
              ignore: master
          requires:
            - review-PR
      - review-staging:
          filters:
            branches:
              ignore: master
          # Visually check site
          type: approval
          requires:
            - deploy-to-staging
      - deploy-to-prod:
          filters:
            branches:
              only: master
